#!/bin/sh
#SBATCH -N 1      # nodes requested
#SBATCH -n 1      # tasks requested
#SBATCH --partition=Standard
#SBATCH --gres=gpu:1
#SBATCH --mem=12000  # memory in Mb
#SBATCH --time=0-08:00:00

export CUDA_HOME=/opt/cuda-9.0.176.1/

export CUDNN_HOME=/opt/cuDNN-7.0/

export STUDENT_ID=$(whoami)

export LD_LIBRARY_PATH=${CUDNN_HOME}/lib64:${CUDA_HOME}/lib64:$LD_LIBRARY_PATH

export LIBRARY_PATH=${CUDNN_HOME}/lib64:$LIBRARY_PATH

export CPATH=${CUDNN_HOME}/include:$CPATH

export PATH=/home/${STUDENT_ID}/.pkg/bin:/home/${STUDENT_ID}/.bin/Python-3.7.2:${CUDA_HOME}/bin:/home/${STUDENT_ID}/miniconda3/envs/mlp/bin:/home/${STUDENT_ID}/miniconda3/bin:${PATH}

export PYTHONPATH=$PATH:.

mkdir -p /disk/scratch/${STUDENT_ID}


export TMPDIR=/disk/scratch/${STUDENT_ID}/
export TMP=/disk/scratch/${STUDENT_ID}/

export LOTSS_DATA_DIR=/home/${STUDENT_ID}/mlp/dataset    # MAKE SURE THIS IS RIGHT

mkdir -p ${TMP}/datasets/
export DATASET_DIR=${TMP}/datasets/

# Activate the relevant virtual environment:

source /home/${STUDENT_ID}/miniconda3/bin/deactivate mlp
source /home/${STUDENT_ID}/miniconda3/bin/activate mlp
cd /home/${STUDENT_ID}/mlp/github/AstroNNomy             # THIS TOO

